# Qa Construct X the matrix

In [66]:
# Qa

import numpy as np

y = np.array([1,2,3,4]) # NOTE:  you'll need this later

# TODO..create and print the full matrix
x1 = np.array([1,2,3])
x2 = np.array([4,2,1])
x3 = np.array([3,8,5])
x4 = np.array([-9,-1,0])

# x1_t = np.transpose(x1)
# x2_t = np.transpose(x2)
# x3_t = np.transpose(x3)
# x4_t = np.transpose(x4)

X = np.array([x1, x2, x3, x4])

print(f"Design matrix = {X}")


Design matrix = [[ 1  2  3]
 [ 4  2  1]
 [ 3  8  5]
 [-9 -1  0]]


## Qb Implement L1, L2 and L2Dot

In [67]:
# Qb

import math


def L1(vector):
    assert vector.ndim == 1, "Type not a vector"
    sum = 0
    for x in vector:
        sum += math.fabs(x)
    assert sum >= 0, "Sum can't be negative"
    return sum

def L2(vector):
    assert vector.ndim == 1, "Type not a vector"
    sum = 0
    for x in vector:
        sum += x**2
    assert sum >= 0, "Sum can't be negative"
    return sum**0.5

def L2Dot(vector):
    assert vector.ndim == 1, "Type not a vector"
    return np.dot(np.transpose(vector), vector)**0.5

    
# TEST vectors: here I test your implementation...calling your L1() and L2() functions
tx=np.array([1, 2, 3, -1])
ty=np.array([3,-1, 4,  1])

print(f"L1 function = {L1(tx)}")
print(f"L2 function = {L2(tx)}")

print(f"numpy function ord: 1 = {np.linalg.norm(tx, ord=1)}")
print(f"numpy function ord: 2 = {np.linalg.norm(tx, ord=2)}")

d1=L1(tx-ty)
d2=L2(tx-ty)


expected_d1=8.0
expected_d2=4.242640687119285

print(f"tx-ty={tx-ty}, d1-expected_d1={d1-expected_d1}, d2-expected_d2={d2-expected_d2}")

eps=1E-9 
# NOTE: remember to import 'math' for fabs for the next two lines..
assert math.fabs(d1-expected_d1)<eps, "L1 dist seems to be wrong" 
assert math.fabs(d2-expected_d2)<eps, "L2 dist seems to be wrong" 

print("OK(part-1)")

# comment-in once your L2Dot fun is ready...
d2dot=L2Dot(tx-ty)
print("d2dot-expected_d2=",d2dot-expected_d2)
assert math.fabs(d2dot-expected_d2)<eps, "L2Ddot dist seem to be wrong" 
print("OK(part-2)")

L1 function = 7.0
L2 function = 3.872983346207417
numpy function ord: 1 = 7.0
numpy function ord: 2 = 3.872983346207417
tx-ty=[-2  3 -1 -2], d1-expected_d1=0.0, d2-expected_d2=0.0
OK(part-1)
d2dot-expected_d2= 0.0
OK(part-2)


## Qc Implement RMSE 

In [68]:
# Qc

# The L2 function takes the square rooth of the return value before returning, so we have to square the return value once again, to make it fit with the RMSE equation 
def RMSE(x,y):
    assert x.size == y.size, "Vectors not same size"
    ret = 1/x.size * (L2((x-y))**2)
    assert ret >= 0, "return value can't be negative"
    return ret**0.5 


# Dummy h function:
def h(X):    
    if X.ndim!=2:
        raise ValueError("excpeted X to be of ndim=2, got ndim=",X.ndim)
    if X.shape[0]==0 or X.shape[1]==0:
        raise ValueError("X got zero data along the 0/1 axis, cannot continue")
    return X[:,0]

# Calls your RMSE() function:
r=RMSE(h(X),y)

# TEST vector:
eps=1E-9
expected=6.57647321898295
print(f"RMSE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "your RMSE dist seems to be wrong" 

print("OK")

RMSE=6.576473218982953, diff=2.6645352591003757e-15
OK


## Qd Implement MAE

In [69]:
# Qd
def MAE(x,y):
    assert x.size == y.size, "Vectors not same size"
    ret = 1/x.size * L1(x-y)
    assert ret >= 0, "Return value can't be negative"
    return ret

# Calls your MAE function:
r=MAE(h(X), y)

# TEST vector:
expected=3.75
print(f"MAE={r}, diff={r-expected}")
assert math.fabs(r-expected)<eps, "MAE dist seems to be wrong" 

print("OK")

MAE=3.75, diff=0.0
OK


## Qe Pythonic code

Pythonic code has been implemented for all the functions. Making asserts for types and valid values of input and return values.

## Qf Conclusion

In these exercises, we dove into the core math concepts that underpin machine learning. We explored vectors and matrices and how we represent them in Python. Norms, which are essentially ways to measure distances. These specific norms are L1 and L2 norms, which describes two ways of measuring distance between two vectors. L1 returns the distance measure the shortest distance using horizontal and vertical lines (if 2D) (lines that follow the axis of the vector or matrix). L2 also returns distance between two vectors, but has the "freedom" of using the shortest distance possible, without being restricted by the axis. For L2, in 2D space for example, it would be able to measure the distance using diagonal lines.

These functions can be used to measure the distance from the $h(X)$ and $y_{pred}$ for determining how good your machine learning model is. 
The MAE function was implemented aswell. This formula uses the norm distances from between the two vectors (L1), and outputs the absolute value of the mean of the errors. This gives another perspective of the errors of the ML model. RMSE has the same functionality, but using the L2 function as the distance. That means the euclidean distance between the vectors.

Thereafter we used the opportunity of creating "pythonic" code, which rides on the principle of throwing errors as soon as possible. Instilling it this early in the course gives a good foundation for reliable python development to come.